services:
  backend:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: podrabotka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7FMhKb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s